### ISSUE TITLE
How to interpret perf_mod and contrast_models results?

### ISSUE THREAD

**Issue by jroberayalas** [topepo/tidyposterior#13]
I was just wondering if it's possible to interpret the results from the `perf_mod` and `contrast_models` functions using 95% posterior intervals.

Also, I'm not sure if the posterior distribution should (in general) cover the different samples obtained from the `rsample` package. For example, running some code for comparison of different Cox models (for survival analysis), I obtained the plot below. The different concordance indexes for 50 resamples of Monte Carlo cross-validation are shown in blue, and the lines in black corresponds to the posterior distribution after running `perf_mod`. What intrigues me is that the distribution seems too narrow with respect to the spread of the different resamples.

![screen shot 2018-01-02 at 19 24 50](https://user-images.githubusercontent.com/8128586/34496935-66f18668-eff3-11e7-8660-79dcad692f6c.png)

Sorry for asking this, it's the first time I use the stan R package, and trying to adopt a more Bayesian approach (and mentality) rather than the typical p-values.

**Comment by topepo** [comment]
The resamples are realizations of the populations that we are interested in. The distributions are the posterior distributions of the population _parameters_. 

It is analogous to the non-Bayesian case. If you sample a Gaussian distribution, the spread of the data distribution is about `sqrt(n)` wider than the sampling distribution of the population mean parameter. 

If you want a distribution that is more reflective of the resamples, the posterior _predictive_ interval would show the distribution that reflects what we would expect to see for a new resample. [This](https://stats.stackexchange.com/questions/169623/what-non-bayesian-methods-are-there-for-predictive-inference) is a good discussion of the differences. You can get these by using the `rstanarm:: predictive_interval` function on the `perf_mod$stan` object.   (I mistakenly used the wrong function when I first started using the package)

**Comment by jroberayalas** [comment]
Thank you! Makes perfect sense. I thought the distributions were trying to describe the resamples, but now it's clearer.

One final question on this. Given that we have paired metric resamples between 2 different models that used the same Monte Carlo cross-validation, is it sensible to compare models by computing probabilities like P(concordance_M1 > concordance_M2) using the number of resamples where the concordance of M1 is bigger than M2 and then dividing by the total number of resamples?

**Comment by topepo** [comment]
You could do that but I think that the sampling properties of that approach would be much worse than using the posterior probabilities to estimate the same thing.

**Comment by jroberayalas** [comment]
Thank you! I learned a lot!
